version: '3.9'

services:
  traefik:
    container_name: traefik
    image: traefik:v3.0
    command:
      - "--api.insecure=true"
#      - "traefik.http.middlewares.auth.basicauth.users=admin:$apr1$8v29g4Xx$2tcqmHP9atbg41MMYLL2L1" # mahmoud123456
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/etc/traefik/acme/acme.json
    labels:
      - "traefik.enable=true"
#      - "traefik.http.routers.dashboard-http.entrypoints=web"
#      - "traefik.http.routers.dashboard-http.service=api@internal"
#      - "traefik.http.routers.dashboard.entrypoints=websecure"
#      - "traefik.http.routers.dashboard-http.rule=Host(`portal.trio-travel.com`)"
#      - "traefik.http.routers.dashboard.rule=Host(`portal.trio-travel.com`)"
#      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
#      - "traefik.http.routers.dashboard.service=api@internal"
#      - "traefik.http.routers.dashboard.tls=true"
#      - "traefik.http.routers.dashboard.middlewares=auth"
