version: '3.9'

services:
  php-apache:
    build: .
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php-apache.rule=Host(`portal.trio-travel.com`)"
      - "traefik.http.services.php-apache.loadbalancer.server.port=80"
      - "traefik.http.routers.php-apache.tls.certresolver=letsencrypt"
    volumes:
      - ./:/var/www/html
networks:
  test-network:
    external: true
