version: '3.9'

services:
  php-apache-api:
    build:
        context: .
        dockerfile: Dockerfile-api
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php-apache-api.rule=Host(`api.black-devil.click`)"
      - "traefik.http.services.php-apache-api.loadbalancer.server.port=80"
      - "traefik.http.routers.php-apache-api.tls.certresolver=letsencrypt"
    volumes:
      - ./api:/var/www/html
networks:
  test-network:
    external: true
